import Hazel from "hazel"

Hazel.init_printerArr()
Hazel.init_evaluatorArr()

let p1 = Hazel.buildBoolLit(true);
let p2 = Hazel.buildBoolLit(true);
let p3 = Hazel.buildEmptyHole(312);
let prog = Hazel.buildBinBoolOp(Hazel.And, p1, p3);

//Hazel.print_prog(prog)
// let prog = Hazel.evaluate(prog)
// print("finish first step")
// Hazel.print_prog(prog)
//print(p1)
//print(Hazel.testgrain(Array.make(4, 7)))

